export const PRODUCTS = [
  {
    name: "Nova Desk Lamp",
    id: 1,
    category: "Workspace",
    description: "A compact aluminum lamp with warm dimming, USB-C power, and a soft touch control.",
    price: 64,
    stock: 18,
    accent: "#14b8a6",
  },
  {
    name: "Arc Travel Pack",
    id: 2,
    category: "Carry",
    description: "Weather-resistant daily pack with a protected laptop sleeve and quick-access pockets.",
    price: 128,
    stock: 9,
    accent: "#f97316",
  },
  {
    name: "Pulse Headphones",
    id: 3,
    category: "Audio",
    description: "Lightweight over-ear headphones with balanced sound and long battery life.",
    price: 212,
    stock: 12,
    accent: "#6366f1",
  },
  {
    name: "Nova Desk Lamp",
    id: 1,
    category: "Workspace",
    description: "A compact aluminum lamp with warm dimming, USB-C power, and a soft touch control.",
    price: 64,
    stock: 18,
    accent: "#14b8a6",
  },
  {
    name: "Arc Travel Pack",
    id: 2,
    category: "Carry",
    description: "Weather-resistant daily pack with a protected laptop sleeve and quick-access pockets.",
    price: 128,
    stock: 9,
    accent: "#f97316",
  },
  {
    name: "Pulse Headphones",
    id: 3,
    category: "Audio",
    description: "Lightweight over-ear headphones with balanced sound and long battery life.",
    price: 212,
    stock: 12,
    accent: "#6366f1",
  },
];
